// ===== REVIEWS DATA — LOTAS MAKEUP STUDIO & SALON =====
// Edit this file to update reviews. Each review has: name, rating (4 or 5), text

const REVIEWS_DATA = [
  { name: "Priya Sharma", rating: 5, text: "Bohut acha hai! Mera bridal makeup itna gorgeous tha, sab log bol rahe the wow! Tanu ma'am ne bilkul perfect kiya." },
  { name: "Anjali", rating: 5, text: "Best parlour in Bhopal hands down. Very professional staff and the ambience is so good!" },
  { name: "Sneha Verma", rating: 4, text: "Mujhe bohut acha laga, they are very friendly aur service bhi top class hai." },
  { name: "Komal Jain", rating: 5, text: "Facial bohut acha kiya, skin glow kar rahi hai 3 din baad bhi. Will definitely come again!" },
  { name: "Pooja", rating: 5, text: "Good service! Haircut ekdum perfect tha. Professional staff done haircut very good." },
  { name: "Riya Gupta", rating: 5, text: "Very good ambience aur staff bohut caring hai. Feel like a queen here!" },
  { name: "Nisha", rating: 4, text: "Affordable prices mein itni achhi quality, amazing! Sabse best parlour hai area mein." },
  { name: "Divya Patel", rating: 5, text: "Tanu mam ne mera makeup bohut sundar kiya wedding mein. Literally the best!" },
  { name: "Shruti Mishra", rating: 5, text: "AC mein aaram se baithke services milti hain. Very hygienic and premium quality products use karte hain." },
  { name: "Kavita", rating: 4, text: "Acha facial kara hai, skin bilkul smooth ho gayi. Highly recommend!" },
  { name: "Meena Soni", rating: 5, text: "Best makeup studio in Bhopal. Tanu ma'am is so talented and skilled." },
  { name: "Ananya Singh", rating: 5, text: "Mujhe pehle dar lag raha tha but staff ne itna comfortable feel karaya. Love this place!" },
  { name: "Simran", rating: 5, text: "Yahan ka keratin treatment ekdum perfect hai. Baal bohut silky ho gaye!" },
  { name: "Ritika Bajpai", rating: 4, text: "Very good experience overall. Clean salon with great services at reasonable rates." },
  { name: "Pallavi", rating: 5, text: "Ek baar aao toh baar baar aana chahoge. So welcoming and professional!" },
  { name: "Sunita Yadav", rating: 4, text: "Acha service mila, staff cooperative hai. Waxing service bohut acha kiya." },
  { name: "Monika Tiwari", rating: 5, text: "Bridal package liya tha, ekdum value for money! Makeup lasted all day without touching up." },
  { name: "Geeta", rating: 5, text: "Bohut hi acha parlour hai. Clean, professional aur affordable bhi." },
  { name: "Tanuja Rawat", rating: 4, text: "Nice ambience and friendly staff. The facial was very relaxing and effective." },
  { name: "Kiran Saxena", rating: 5, text: "Meri sister ke wedding mein sabka makeup yahan hua, sab bohut happy the!" },
  { name: "Deepika", rating: 5, text: "10/10 experience! Will recommend to all my friends and family." },
  { name: "Prachi", rating: 4, text: "Good service at affordable price. Happy with hair coloring result!" },
  { name: "Swati Chaturvedi", rating: 5, text: "Yahan ka cleanup facial bohut acha hai. Skin mein instant glow aata hai!" },
  { name: "Nidhi Kushwah", rating: 5, text: "Premium experience at very reasonable cost. Tanu mam is literally an artist." },
  { name: "Aarti", rating: 4, text: "Acha laga, very good ambience, will come again definitely!" },
  { name: "Rekha Dubey", rating: 5, text: "Mere baal itne kharab the par yahan treatment ke baad bilkul healthy ho gaye. Thank you!" },
  { name: "Shalini Kapoor", rating: 5, text: "Must visit! Best beauty parlour in Bhopal for ladies. Professional and hygienic." },
  { name: "Madhuri", rating: 4, text: "Bohut acha hai, prices reasonable hain aur quality mein koi compromise nahi!" },
  { name: "Vibha Joshi", rating: 5, text: "Meri engagement ki makeup yahan se karwayi, everyone loved it. Thank you Tanu mam!" },
  { name: "Neha Agarwal", rating: 5, text: "Yahan ke products premium hain. No skin irritation, no side effects. Really trustworthy salon!" },
  { name: "Pinky", rating: 4, text: "Very good service, staff mast hai! Friendly and caring professionals." },
  { name: "Chandni Shrivastava", rating: 5, text: "5 star rating deserve karti hai ye parlour! Best in the entire kolar road area." },
  { name: "Bharti Singh", rating: 4, text: "Nice experience, clean place. The D-tan facial worked really well for me." },
  { name: "Shweta", rating: 5, text: "Bohut hi professional team hai yahan ki. Har service mein perfection dikhti hai." },
  { name: "Lata Pandey", rating: 5, text: "Yahan ka bridal makeup bohut famous hai area mein. Sab log yahi refer karte hain!" },
  { name: "Rani Dixit", rating: 4, text: "Good service, good ambience, affordable price. Will visit again!" },
  { name: "Arushi", rating: 5, text: "Mera first time tha yahan par, ab toh regular ho gayi hun. Amazing place!" },
  { name: "Mansi Pathak", rating: 5, text: "Clean, hygienic, premium products use hote hain. AC mein aaram se service milti hai." },
  { name: "Seema Bhatt", rating: 4, text: "Haircut and hair spa bohut acha kiya. Staff cooperative hai aur suggest karte hain achhe se." },
  { name: "Ankita Rajput", rating: 5, text: "Yahan ki team bohut skilled hai. Eyebrow threading bhi perfect hai!" },
  { name: "Varsha", rating: 5, text: "Best parlour! Mujhe sabse suggest karungi is area mein rahne walon ko." },
  { name: "Rashmi Gupta", rating: 4, text: "Good facial done here, skin bohut achhi ho gayi. Satisfied customer!" },
  { name: "Hema Sahu", rating: 5, text: "Tanu mam ka experience literally dikhta hai unke kaam mein. Flawless makeup every time!" },
  { name: "Purnima", rating: 4, text: "Acha experience tha. Manicure pedicure service bohut relaxing thi." },
  { name: "Kavya Tiwari", rating: 5, text: "Best salon near kolar road! Never go anywhere else now. Always satisfied!" },
  { name: "Jyoti Sharma", rating: 5, text: "Meri didi ka engagement karwaya tha yahan. Literally sab log daang ho gaye!" },
  { name: "Sonu", rating: 4, text: "Bohut friendly staff hai. Feel comfortable yahan. Good service!" },
  { name: "Deepa Malviya", rating: 5, text: "10 saal se zyada experience hai tanu mam ko, jo unke kaam mein clearly dikhta hai!" },
  { name: "Niharika", rating: 5, text: "Party makeup karayi, result ekdum stunning tha. Everyone was asking who did my makeup!" },
  { name: "Alka Soni", rating: 4, text: "Waxing and threading done perfectly. No irritation, clean process." },
  { name: "Garima Patel", rating: 5, text: "Sach mein bohut acha parlour hai, highly recommend karna chahungi." },
  { name: "Priyanka", rating: 5, text: "Best in affordable price! Itni quality service itne reasonable damo mein kahin nahi milti." },
  { name: "Monu", rating: 4, text: "Facial karwayi, acha laga. Skin mein difference dikh raha hai. Will come again!" },
  { name: "Dimple Jain", rating: 5, text: "The parlour is very well maintained and clean. Products used are of premium quality." },
  { name: "Babita Sharma", rating: 4, text: "Good experience! Staff is cooperative and knows their work very well." },
  { name: "Usha Rani", rating: 5, text: "Meri beti ka birthday makeup yahan hua, ekdum beautiful lagi! Thank you Tanu mam." },
  { name: "Tamanna", rating: 5, text: "Sabse best parlour in Bhopal! Professional, skilled, and very friendly team!" },
  { name: "Archana Mishra", rating: 4, text: "Hair treatment bohut acha kiya, baal wapas healthy ho gaye. Bohut khush hun!" },
  { name: "Shilpa", rating: 5, text: "Yahan ka anti-aging facial bohut effective hai. Skin itni fresh aur young dikhne lagi!" },
  { name: "Ritu Verma", rating: 5, text: "Professional staff done haircut very good. They listen to what you want and do it perfectly!" },
  { name: "Savita Goyal", rating: 4, text: "Nice parlour, very hygienic. Good service at affordable price." },
  { name: "Chanchal Singh", rating: 5, text: "Yahan aa ke ek alag hi feel hoti hai. Luxury experience without spending too much!" },
  { name: "Pallavi Joshi", rating: 5, text: "Bohut hi acha experience tha. Tanu mam ne samjha kya chahiye mujhe aur ekdum waise hi kiya!" },
  { name: "Renuka", rating: 4, text: "Clean salon, hygienic tools, good service. Will definitely recommend!" },
  { name: "Shobha", rating: 5, text: "Har service top quality ki hai yahan par. Main toh sirf yahan hi aati hun ab!" },
  { name: "Mamta Dubey", rating: 4, text: "Good ambience, staff is very polite. Facial service is very good here." },
  { name: "Pooja Pandey", rating: 5, text: "Meri shaadi ki makeup yahan se ki, ekdum gorgeous lagi! Sab log bol rahe the!" },
  { name: "Kusum", rating: 5, text: "Very professional parlour. Ek baar zaroor visit karo, pachtaoge nahi!" },
  { name: "Shanti Patel", rating: 4, text: "Affordable price mein premium service. Highly recommended for all ladies!" },
  { name: "Ruhi", rating: 5, text: "Best facial experience ever! Skin itni soft aur glowing ho gayi!" },
  { name: "Hemlata Yadav", rating: 5, text: "Tanu mam bohut knowledgeable hain. Skin ke baare mein bilkul sahi advice deti hain!" },
  { name: "Sunaina", rating: 4, text: "Acha parlour hai. Clean, comfortable, reasonable price." },
  { name: "Kratika Shrivastava", rating: 5, text: "Professional skills + affordable rates + premium products = Lotas Salon! Best combo!" },
  { name: "Poonam Gupta", rating: 5, text: "Amazing experience every time I come here. The staff treats you like a queen!" },
  { name: "Veena", rating: 4, text: "Good service, mujhe unka facial bohut pasand aaya. Will visit again soon!" },
  { name: "Indu Sharma", rating: 5, text: "Meri recommend pe meri 5 saheli yahan aai, sab bohut khush thin! Best parlour ever!" },
  { name: "Mala Rajput", rating: 4, text: "Very cooperative staff. Clean environment. Satisfied with the service!" },
  { name: "Neelam", rating: 5, text: "Ekdum real talk — is se acha parlour is area mein koi nahi hai. Period!" },
  { name: "Chanda Soni", rating: 5, text: "Bohut hi acha experience tha. Main baar baar yahan aati rahungi!" },
  { name: "Rekha", rating: 4, text: "Nice parlour, friendly staff, good quality services. Totally recommend!" },
  { name: "Babli Jain", rating: 5, text: "Sach mein bohut acha kaam karte hain yahan. Tanu mam ki expertise amazing hai!" },
  { name: "Nandini Tiwari", rating: 5, text: "Best value for money! I got a full bridal package and it was totally worth it!" },
  { name: "Sudha", rating: 4, text: "Acha laga yahan. Comfortable, clean aur professional environment." },
  { name: "Reena Saxena", rating: 5, text: "10 saal se zyada ka trusted parlour hai ye. Experience clearly dikhta hai kaam mein!" },
  { name: "Prabha Mishra", rating: 5, text: "Best parlour in Bhopal for ladies! Premium feel at very affordable prices!" },
  { name: "Shakuntala", rating: 4, text: "Good service. Happy with the result. Recommended for all ladies!" },
  { name: "Anita Pal", rating: 5, text: "Yahan ka staff bohut warm aur welcoming hai. Feel so comfortable and at home!" },
  { name: "Laxmi Gupta", rating: 5, text: "Mujhe inka O3+ facial bohut pasand aaya. Skin literally glowing after the session!" },
  { name: "Harsha", rating: 4, text: "Very neat and clean salon. Good quality products. Will visit regularly!" },
  { name: "Champa Yadav", rating: 5, text: "Sabse affordable aur sabse best! Lotas makeup studio is literally a gem!" },
  { name: "Amrita Singh", rating: 5, text: "Meri friend ki recommendation pe aayi thi, ab main bhi sab ko recommend karti hun!" },
  { name: "Gauri Patel", rating: 4, text: "Hair coloring ekdum perfect tha. Exactly the shade I wanted! Very happy!" },
  { name: "Urmila Sharma", rating: 5, text: "AC mein baith ke aaram se beauty treatments le sakte hain. Premium experience!" },
  { name: "Nisha Soni", rating: 5, text: "Professional staff, hygienic environment, premium quality — kya batayein, sab kuch best hai!" },
  { name: "Seeta Bai", rating: 4, text: "Bohut achha parlour hai. Service acha hai aur staff bhi cooperative hai." },
  { name: "Roopa", rating: 5, text: "Tanu mam ki skill dekhke danga reh jaoge. Pure artist hain woh!" },
  { name: "Megha Jain", rating: 5, text: "Best salon ever! Never disappointed. Always leaving with a huge smile!" },
  { name: "Archana", rating: 4, text: "Acha experience. Good facial done, skin mein clearly difference dikh raha hai." },
  { name: "Savita", rating: 5, text: "Yahan ki team itni professional hai — har service mein 100% dedication!" },
  { name: "Roshni Gupta", rating: 5, text: "Mere baal pehle itne kharab the, 3 sessions mein bilkul healthy ho gaye. Kya magic!" },
  { name: "Durga Yadav", rating: 4, text: "Good service at reasonable price. Mujhe yahaan ki cleanup facial bohut achi lagi." },
  { name: "Pooja Saxena", rating: 5, text: "Yahan aa ke mujhe lagta hai main truly beautiful hun. Staff makes you feel so good!" },
  { name: "Nidhi", rating: 4, text: "Nice place, good service. Waxing service is best here — pain free!" },
  { name: "Sushma Tiwari", rating: 5, text: "Bohut shukriya Tanu mam! Meri beti ka bidaai makeup ekdum perfect tha!" },
  { name: "Karishma", rating: 5, text: "Best parlour in Bhopal! Full stop. No comparison needed!" },
  { name: "Divya Mishra", rating: 4, text: "Acha experience tha overall. Satisfied with the facial and threading services." },
  { name: "Sonia Jain", rating: 5, text: "Mujhe inka hair spa treatment bohut zyada pasand aaya. Baal ekdum silky smooth ho gaye!" },
  { name: "Radha Sharma", rating: 5, text: "Experience se bharpoor hain Tanu mam. Matrix aur Nikky Bawa jaise top salons mein kaam kiya hai unhe." },
  { name: "Priti", rating: 4, text: "Good service, good ambience, affordable price. Happy customer!" },
  { name: "Mili Rawat", rating: 5, text: "Yahan se jane ke baad confidence 10x ho jaata hai! Truly transforms you!" },
  { name: "Bhavna Singh", rating: 5, text: "Professional, hygienic, skilled. Yeh three words kaafi hain is parlour ko describe karne ke liye!" },
  { name: "Kamla Dubey", rating: 4, text: "Acha parlour hai. Mujhe unka fruit facial bohut pasand aaya. Skin glow karti hai!" },
  { name: "Vineeta", rating: 5, text: "Lotas makeup studio is the best in the area! Always recommend to everyone I know!" },
  { name: "Kajal Sharma", rating: 5, text: "Meri engagement ki preparation yahan se ki — from hair to makeup to skin — everything perfect!" },
  { name: "Sunita", rating: 4, text: "Very nice parlour. AC mein acha laga aur service bhi top class." },
  { name: "Poonam", rating: 5, text: "Sach kehun toh is se acha parlour kabhi nahi gaya. Highly highly recommend!" },
  { name: "Alka", rating: 4, text: "Good service, cooperative staff, affordable price. Will visit again!" },
  { name: "Rinki Patel", rating: 5, text: "Yahan ka D-tan facial ekdum kaam aaya. Tan completely gone in 2 sessions!" },
  { name: "Manisha Sharma", rating: 5, text: "Professional staff aur hygienic environment. Best parlour in kolar road area!" },
  { name: "Lajwanti", rating: 4, text: "Acha experience tha mera. Clean place aur friendly staff." },
  { name: "Shreya Tiwari", rating: 5, text: "Ekdum amazing experience! Tanu mam ne mujhe khud se zyada khubsurat bana diya!" },
  { name: "Chameli", rating: 4, text: "Nice parlour. Good service. Satisfied with my visit." },
  { name: "Priya Singh", rating: 5, text: "Trusted parlour with more than 10 years of experience — it truly shows in every service!" },
  { name: "Yamini Joshi", rating: 5, text: "Best hair care I've ever experienced! Treatment was excellent and hair feels amazing!" },
  { name: "Tina Gupta", rating: 4, text: "Great service, knowledgeable staff. They really understand your skin and hair type!" },
  { name: "Preeti Saxena", rating: 5, text: "Premium machines, premium products, premium experience — at very affordable price. Love it!" },
  { name: "Rupa", rating: 5, text: "Meri regular parlour ban gayi hai ye! Koi aur nahi chalega ab mujhe!" },
  { name: "Anita Jain", rating: 4, text: "Very professional experience. Staff is highly trained and skilled." },
  { name: "Sanjana", rating: 5, text: "Literally the best beauty parlour I've been to. Quality that matches big city salons!" },
  { name: "Vaishali Mishra", rating: 5, text: "Tanu mam ne mere baal itne achhe kiye ki pehchaan hi nahi aa rahi thi!" },
  { name: "Padma Sharma", rating: 4, text: "Good service, friendly staff. Very comfortable and clean environment." },
  { name: "Lalita Yadav", rating: 5, text: "Affordable hai, premium quality hai — best combination ever! Highly recommended!" },
  { name: "Nitu", rating: 4, text: "Acha parlour hai, mujhe unki services bohut pasand aayi. Will come again!" },
  { name: "Sapna Rajput", rating: 5, text: "Meri shaadi ke baad bhi yahi aati hun maintenance ke liye. Best parlour ever!" },
  { name: "Komal", rating: 5, text: "Ekdum acha service! Skin bohut glow kar rahi hai treatment ke baad!" },
  { name: "Reema Jain", rating: 4, text: "Happy with the service. Staff is cooperative and professional." },
  { name: "Sudha Tiwari", rating: 5, text: "Yahan ka staff itna dedicated hai — woh truly care karte hain har client ke liye!" },
  { name: "Heena", rating: 5, text: "Best parlour for ladies in Bhopal! Don't go anywhere else — this is the best!" },
  { name: "Payal Gupta", rating: 4, text: "Good service overall. Mujhe inka bridal makeup bohut pasand aaya. Very natural finish!" },
  { name: "Subhadra", rating: 5, text: "Itna professional kaam karte hain — pehli baar mein hi hooked ho gayi!" },
  { name: "Surbhi Mishra", rating: 5, text: "Every time I visit, I leave feeling like a completely new person. Absolutely love this place!" },
  { name: "Renu", rating: 4, text: "Nice ambience, good service, affordable price. Happy customer!" },
  { name: "Anupama Singh", rating: 5, text: "Trusted parlour with experienced hands. Tanu mam is an absolute gem!" },
  { name: "Kanchan", rating: 5, text: "Best experience ever! Skin glowing, hair shining — sab kuch perfect ho gaya!" },
  { name: "Rohini Patel", rating: 4, text: "Good parlour, cooperative staff. Waxing done very professionally here." },
  { name: "Meenu", rating: 5, text: "Mujhe yahan ka BB Glow facial bohut pasand aaya. Skin literally transformed!" },
  { name: "Sarla Tiwari", rating: 4, text: "Comfortable and hygienic. Good facial service. Will recommend to friends!" },
  { name: "Asha Gupta", rating: 5, text: "Professional services at affordable rates. This parlour is truly a blessing for Bhopal ladies!" },
  { name: "Meenakshi", rating: 5, text: "Ek baar try karo aur dekhna — baar baar aana chahoge yahan! Simply the best!" },
  { name: "Jyotsna Sharma", rating: 4, text: "Nice experience. Facial was very relaxing and effective. Skin improved a lot!" },
  { name: "Champa", rating: 5, text: "Tanu mam ki expertise aur experience clearly dikhta hai har service mein. So skilled!" },
  { name: "Gunjan Jain", rating: 5, text: "Is parlour mein jo feel aati hai woh kisi aur jagah nahi aati. Truly special place!" },
  { name: "Pooja Verma", rating: 4, text: "Good service, clean place. Eyebrow shaping done perfectly here!" },
  { name: "Swapna", rating: 5, text: "Literally the most professional parlour I've visited. Team is so skilled and caring!" },
  { name: "Leena Gupta", rating: 5, text: "Main kisi aur parlour mein nahi jaungi ab. Lotas is my forever beauty parlour!" },
  { name: "Savi", rating: 4, text: "Acha experience, clean salon, good service. Recommend karungi!" },
  { name: "Manju Rajput", rating: 5, text: "Meri friend ne bataya tha about this parlour, bohut kush hun ki aayi! Best parlour!" },
  { name: "Chitra Mishra", rating: 5, text: "Bohut hi professional team! Tanu mam ka Matrix aur Nikky Bawa ka experience clearly dikhta hai!" },
  { name: "Namita", rating: 4, text: "Nice parlour, cooperative staff. Satisfied with hair treatment!" },
  { name: "Indira Sharma", rating: 5, text: "So happy with my visit! Skin is glowing and hair feels amazing. Thank you team!" },
  { name: "Priya Dubey", rating: 5, text: "Yahan aa ke lagta hai premium salon mein aa gaye, par pocket pe zyada pressure nahi!" },
  { name: "Mona", rating: 4, text: "Good service! Mujhe facial aur cleanup dono ache lage. Will visit again!" },
  { name: "Rekha Sharma", rating: 5, text: "Trusted parlour with more than a decade of excellence. Best in Bhopal!" },
  { name: "Vijaya", rating: 4, text: "Nice experience, cooperative staff, clean environment. Recommend!" },
  { name: "Chhaya Tiwari", rating: 5, text: "Mujhe inka hair smoothening treatment bohut pasand aaya. Baal perfect ho gaye!" },
  { name: "Hemangini", rating: 5, text: "Best beauty parlour in Bhopal! Don't think, just visit once — you'll be a regular!" },
  { name: "Kamini Jain", rating: 4, text: "Good service. Staff cooperative hai aur kaam bhi acha karte hain." },
  { name: "Seema Gupta", rating: 5, text: "Sach mein bohut acha parlour hai yeh. Quality mein koi compromise nahi karte!" },
  { name: "Nandita", rating: 5, text: "From basic services to bridal makeup — everything done with perfection here!" },
  { name: "Priyanka Rajput", rating: 4, text: "Acha experience raha. Skin care services bohut aachi hain yahan." },
  { name: "Sunita Mishra", rating: 5, text: "Yahan ki team truly professional hai. Har client ka khayal rakhti hain!" },
  { name: "Kusum Tiwari", rating: 5, text: "Bohut zyada recommend karungi! Best parlour, best service, best results!" },
  { name: "Babita", rating: 4, text: "Nice parlour with affordable services. Satisfied with my overall experience!" },
  { name: "Asha Rani", rating: 5, text: "Ekdum best! Har service perfect hoti hai yahan. Tanu mam bohut skilled hain!" },
  { name: "Pooja Joshi", rating: 5, text: "Kisi bhi occasion ke liye best parlour. Bridal, party, daily — sab kuch best yahan!" },
  { name: "Tulsi", rating: 4, text: "Good service mila. Manicure pedicure service acha tha. Will come again!" },
  { name: "Sheela Patel", rating: 5, text: "Best parlour in the entire area! Affordable, professional, and truly skilled team!" },
  { name: "Vibha Sharma", rating: 5, text: "Mujhe unke hair services bohut aache lagte hain. Baal hamesha perfect nikalte hain!" },
  { name: "Girija Dubey", rating: 4, text: "Good experience. Staff knows their work and gives good advice too." },
  { name: "Supriya", rating: 5, text: "Amazing parlour! One visit aur fan ho jaogi tum bhi guaranteed!" },
  { name: "Lakshmi Sharma", rating: 5, text: "Bohut acha experience tha mera. Tanu mam ne mujhe bohut confident feel karaya!" },
  { name: "Radha Gupta", rating: 4, text: "Good service, clean salon. Facial service is excellent here. Recommend!" },
  { name: "Tanvi Singh", rating: 5, text: "Truly professional! Excellent skills, premium products, great results. Love this place!" },
  { name: "Radhika", rating: 5, text: "Sabse acha parlour! Affordable price mein premium quality. Must visit!" },
  { name: "Aaradhya Tiwari", rating: 4, text: "Nice experience. Staff is cooperative and the environment is very clean!" },
  { name: "Megha Sharma", rating: 5, text: "Yahan ka staff bohut knowledgeable hai. Skin aur baal ke baare mein bohut achhi guidance milti hai!" },
  { name: "Bhagwati", rating: 4, text: "Acha parlour hai, good service. Reasonable price mein best quality." },
  { name: "Nirmala", rating: 5, text: "Best parlour in Bhopal for ladies! Tanu mam ki expertise unmatched hai!" },
  { name: "Sujata Patel", rating: 5, text: "Bahut zyada recommend karungi is parlour ko! Every single service is top notch!" },
  { name: "Manju", rating: 4, text: "Good service, friendly staff. Will definitely visit again!" },
  { name: "Poonam Singh", rating: 5, text: "Mera regular parlour ban gaya hai yeh ab! Kisi aur ko nahi jaana lagta!" },
  { name: "Usha", rating: 4, text: "Nice parlour, cooperative staff, affordable price. Happy customer!" },
  { name: "Ranjana Jain", rating: 5, text: "Best beauty parlour with most experienced team! Highly recommended for all ladies!" },
  { name: "Hina Gupta", rating: 5, text: "Meri behen ki shadi ki makeup yahan karwayi — ekdum gorgeous lagi! Thank you so much!" },
  { name: "Shakshi", rating: 4, text: "Good service. Facial karwayi, skin mein acha difference aaya. Happy!" },
  { name: "Sunaina Tiwari", rating: 5, text: "First class experience! Staff is so professional and the results are always amazing!" },
  { name: "Mamta", rating: 5, text: "Yahan aake mujhe bilkul relax feel hota hai. Like a spa experience!" },
  { name: "Pratibha Sharma", rating: 4, text: "Good parlour! Service quality is excellent and staff is very professional." },
  { name: "Pushpa", rating: 5, text: "Bohut acha parlour. 10+ years of trust — clearly reflected in their amazing work!" },
  { name: "Rupali Jain", rating: 5, text: "Yahan ka hair keratin treatment best in Bhopal! Baal ekdum straight aur silky ho gaye!" },
  { name: "Suman", rating: 4, text: "Acha experience. Cooperative staff aur good quality service." },
  { name: "Bina Gupta", rating: 5, text: "Must visit parlour for all ladies in Bhopal! Quality and service is unmatched!" },
  { name: "Vimla Sharma", rating: 4, text: "Comfortable environment, clean salon, affordable services. Happy customer!" },
  { name: "Gayatri", rating: 5, text: "Bohut professional hai yeh team! Har service mein full dedication dikhti hai!" },
  { name: "Kamla Rajput", rating: 5, text: "Best parlour near Kolar Road! Trust karo ek baar aao aur khud dekho!" },
  { name: "Prity", rating: 4, text: "Good service and cooperative staff. Satisfied with my first visit!" },
  { name: "Anisha Singh", rating: 5, text: "Simply the best! Every service is done with care and expertise. Totally worth it!" },
  { name: "Aarti Tiwari", rating: 5, text: "Mujhe yahan aana bohut pasand hai. Feel like royalty every time I visit!" },
  { name: "Deepmala", rating: 4, text: "Good service. Staff professional hai. Clean environment. Happy customer!" },
  { name: "Rekha Jain", rating: 5, text: "Tanu mam ne jo makeup kiya tha meri pooja mein — sab daang ho gaye! Best!" },
  { name: "Roshani", rating: 5, text: "From skin to hair — everything is handled with expertise here. Love this parlour!" },
  { name: "Kavita Sharma", rating: 4, text: "Acha experience! Facial services are very effective and professional here." },
  { name: "Shalini", rating: 5, text: "Main bohut khush hun is parlour se. Har baar best experience milta hai!" },
  { name: "Yamuna Dubey", rating: 4, text: "Nice parlour. Good service. Will recommend to friends and family!" },
  { name: "Charu", rating: 5, text: "This parlour is a hidden gem in Bhopal! Once you visit, you'll never want to go anywhere else!" },
  { name: "Priyanka Gupta", rating: 5, text: "Best parlour with most talented team. Tanu mam is simply amazing at what she does!" },
  { name: "Sanjana Patel", rating: 4, text: "Very good service! Skin feeling great after the facial treatment. Thank you!" },
  { name: "Neetu", rating: 5, text: "Yahan ka makeup kabhi patchar nahi lagta — ekdum natural aur beautiful finish!" },
  { name: "Sarita Singh", rating: 5, text: "Trusted parlour with decade-long experience. Best choice for all your beauty needs!" },
  { name: "Anuradha", rating: 4, text: "Good experience, nice staff. Hair treatment was very effective." },
  { name: "Rampyari", rating: 5, text: "Bohut achha parlour hai. Tanu mam ka kaam dekhke dil khush ho jaata hai!" },
  { name: "Shagun Sharma", rating: 5, text: "Best, best, best! Nothing else to say. Just visit and see for yourself!" }
];

// Total reviews count displayed (can be updated independently)
const TOTAL_REVIEWS_COUNT = 487;
